// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Regenerate: GITHUB_TOKEN=ghp_xxx npx ts-node scripts/generate_catalog.ts
// Last generated: 2026-03-11T09:14:25.983Z

import type { BrandId } from './brands';

// ── INTERFACES ──────────────────────────────────────────────────────────────

export interface CatalogProduct {
  id: string;
  sku: string;
  display_name: string;
  collection: string;
  collection_id: string;
  subcollection: string;
  subcollection_id: string;
  description: string;
  description_enhanced: string | null;
  key_ingredients: string[];
  benefit_claims: string[];
  hair_type: string[];
  price: string;
  msrp: string;
  b2b_only: boolean;
  shopify_visibility: string;
  image_filename: string;
  format: string;
  size: string;
}

export interface CatalogSubcollection {
  id: string;
  label: string;
  products: CatalogProduct[];
}

export interface CatalogCollection {
  id: string;
  label: string;
  subcollections: CatalogSubcollection[];
  products: CatalogProduct[];
}

// ── NEURONE CATALOG ─────────────────────────────────────────────────────────

const NEURONE_PRODUCTS: CatalogProduct[] = [
  {
    id: "neurone_capissen_lotion",
    sku: "T067",
    display_name: "Capissen Lotion",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Anti-Caída / Capissen",
    subcollection_id: "anti_cada_capissen",
    description: "Loción Capilar. Prevención Caída del Cabello.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["contribuye al aspecto de densidad y fortaleza del cabello", "cuidado del cuero cabelludo"],
    hair_type: ["thinning", "hair loss concern"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "pending",
    image_filename: "NACLOT.webp",
    format: "spray_applicator_bottle",
    size: "100ml",
  },
  {
    id: "neurone_capissen_shampoo",
    sku: "L033",
    display_name: "Capissen Shampoo",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Anti-Caída / Capissen",
    subcollection_id: "anti_cada_capissen",
    description: "Champú Capilar. Prevención Caída del Cabello.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["contribuye al aspecto de densidad", "cuida el cuero cabelludo", "fortalece la hebra capilar"],
    hair_type: ["thinning", "hair loss concern", "fine hair"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "pending",
    image_filename: "CAPISSEN_400_WEB.png",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_neurone_color",
    sku: "",
    display_name: "Neurone Color",
    collection: "Pro Salon / Colour",
    collection_id: "pro_salon_colour",
    subcollection: "Neurone Color",
    subcollection_id: "neurone_color",
    description: "Tinte Permanente para el Cabello en Crema. Proteína de Quinoa. Nano Tribología Capilar. Fórmula 1+1½.",
    description_enhanced: null,
    key_ingredients: ["quinoa protein", "nano tribology complex", "oxidative dyes"],
    benefit_claims: [],
    hair_type: [],
    price: "0.00",
    msrp: "0.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCOLOR.webp",
    format: "tube_in_box",
    size: "90ml",
  },
  {
    id: "neurone_controller",
    sku: "E006",
    display_name: "Controller",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Cera Gel. Aspecto Húmedo. Extrema Fijación.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["fijación extrema", "efecto wet look", "control total del peinado"],
    hair_type: ["all hair types", "medium to short styles"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NECONTR-3.webp",
    format: "jar_with_lid",
    size: "300g",
  },
  {
    id: "neurone_density_proff",
    sku: "",
    display_name: "Density Proff",
    collection: "Pro Salon / Peroxide",
    collection_id: "pro_salon_peroxide",
    subcollection: "Density Proff",
    subcollection_id: "density_proff",
    description: "Peróxido en Crema. Fórmula de Alta Densidad. Disponible en 20 y 30 volúmenes.",
    description_enhanced: null,
    key_ingredients: ["hydrogen peroxide", "high density formula"],
    benefit_claims: [],
    hair_type: [],
    price: "0.00",
    msrp: "0.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCPLWT-2-1.webp",
    format: "squeeze_bottle",
    size: "1L",
  },
  {
    id: "neurone_depura_shampoo",
    sku: "L021",
    display_name: "Depura Shampoo",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Depura",
    subcollection_id: "depura",
    description: "Champú de Limpieza Profunda. Efecto Purificante.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["limpieza profunda", "efecto purificante", "elimina residuos de producto"],
    hair_type: ["all hair types", "oily scalp", "product buildup"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSDEP-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_derma_roller",
    sku: "PR041",
    display_name: "Derma Roller",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Anti-Caída",
    subcollection_id: "anti_cada",
    description: "Rodillo de Microagujas de Titanio. Auxiliar para tratar el adelgazamiento capilar.",
    description_enhanced: null,
    key_ingredients: ["titanium microneedles"],
    benefit_claims: ["auxiliar para el cuidado del cuero cabelludo", "contribuye al aspecto del cabello"],
    hair_type: ["thinning hair", "hair loss concern"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "pending",
    image_filename: "NACDR.webp",
    format: "box_with_device",
    size: "1 pieza",
  },
  {
    id: "neurone_dy_fazza_color",
    sku: "T062",
    display_name: "DY Fazza Color",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "DY Fazza",
    subcollection_id: "dy_fazza",
    description: "Tratamiento Hidratante Nutritivo de 2 Fases para Cabello Teñido. Sin Enjuague.",
    description_enhanced: null,
    key_ingredients: ["2-phase formula"],
    benefit_claims: ["hidrata el cabello teñido sin enjuague", "nutre la hebra coloreada", "contribuye a prolongar la viveza del color"],
    hair_type: ["color-treated", "dyed", "bleached", "colored hair"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "dyfazzacolor_400_web.png",
    format: "spray_bottle",
    size: "400ml",
  },
  {
    id: "neurone_dy_fazza",
    sku: "T029",
    display_name: "DY Fazza",
    collection: "Moisture",
    collection_id: "moisture",
    subcollection: "DY Fazza",
    subcollection_id: "dy_fazza",
    description: "Tratamiento Hidratante Nutritivo de 2 Fases. Sin Enjuague.",
    description_enhanced: null,
    key_ingredients: ["2-phase formula"],
    benefit_claims: ["hidrata en profundidad", "nutre la hebra", "sin enjuague — fácil de aplicar"],
    hair_type: ["dry", "dehydrated", "curly", "coarse"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "dyfazza_400_web.png",
    format: "spray_bottle",
    size: "400ml",
  },
  {
    id: "neurone_dyfensor_serum",
    sku: "S006",
    display_name: "Dyfensor Hair Restructuring Serum",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Dyfensor",
    subcollection_id: "dyfensor",
    description: "Suero Pro-Reestructuración. Protector De Color.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["reestructura la hebra", "protege el color", "sella la cutícula"],
    hair_type: ["color-treated", "bleached", "damaged"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "DYFENSOR_25ML_WEB.png",
    format: "pump_serum_bottle",
    size: "25ml",
  },
  {
    id: "neurone_dyfensor_shampoo",
    sku: "L024",
    display_name: "Dyfensor Sulfate Free Shampoo",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Dyfensor",
    subcollection_id: "dyfensor",
    description: "Champú Libre de Sulfatos. Protección de Color para Cabello Teñido.",
    description_enhanced: null,
    key_ingredients: ["sulfate-free cleansing agents"],
    benefit_claims: ["libre de sulfatos", "protege el color del cabello teñido", "limpieza suave que prolonga el color"],
    hair_type: ["color-treated", "dyed", "bleached"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "dyfensorsh_400_web.png",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_fanzi_mix",
    sku: "",
    display_name: "Fanzi Mix",
    collection: "Pro Salon / Colour",
    collection_id: "pro_salon_colour",
    subcollection: "Fanzi Mix",
    subcollection_id: "fanzi_mix",
    description: "Color de Fantasía Semi-Permanente.",
    description_enhanced: null,
    key_ingredients: ["direct dyes / pigments"],
    benefit_claims: [],
    hair_type: [],
    price: "0.00",
    msrp: "0.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCFAMIX.webp",
    format: "squeeze_bottle",
    size: "200ml",
  },
  {
    id: "neurone_geometry_cream",
    sku: "E012",
    display_name: "Geometry Cream",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Geometry",
    subcollection_id: "geometry",
    description: "Definición de Rizos. Elasticidad. Efecto Anti-Frizz.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["define los rizos con textura cremosa", "aporta elasticidad", "control del frizz"],
    hair_type: ["curly", "wavy", "coily"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NGEOMC-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_geometry_gel",
    sku: "E008",
    display_name: "Geometry Gel",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Geometry",
    subcollection_id: "geometry",
    description: "Gel Definición de Rizos para el Cabello. Elasticidad. Efecto Anti-Frizz.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["define los rizos", "aporta elasticidad", "efecto anti-frizz"],
    hair_type: ["curly", "wavy", "coily"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NEGEOGE-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_green_100",
    sku: "T109",
    display_name: "Green 100",
    collection: "Restore",
    collection_id: "restore",
    subcollection: "Green 100",
    subcollection_id: "green_100",
    description: "Serum Vegetal para Cabello Extremadamente Reseco, Poroso y Químicamente Procesado. Producto Verde.",
    description_enhanced: null,
    key_ingredients: ["vegetable extracts"],
    benefit_claims: ["restaura la hebra seca y porosa", "nutre con activos vegetales", "favorece la suavidad y flexibilidad"],
    hair_type: ["extremely dry", "porous", "chemically processed", "bleached"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTGREEN-2.webp",
    format: "spray_serum_bottle",
    size: "25ml",
  },
  {
    id: "neurone_humit_mask",
    sku: "T035",
    display_name: "Humit Mask",
    collection: "Moisture",
    collection_id: "moisture",
    subcollection: "Humit",
    subcollection_id: "humit",
    description: "Mascarilla Acondicionadora Pro-Humectación. Cabello Seco y Maltratado.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["hidratación intensa", "acondiciona", "suaviza y aporta brillo"],
    hair_type: ["dry", "damaged", "dehydrated", "over-processed"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "humitmask_400_web.png",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_humit_shampoo",
    sku: "L013",
    display_name: "Humit Shampoo",
    collection: "Moisture",
    collection_id: "moisture",
    subcollection: "Humit",
    subcollection_id: "humit",
    description: "Champú Acondicionador Pro-Humectación. Cabello Seco y Maltratado.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["humectación intensa", "acondiciona mientras limpia", "suaviza la hebra seca"],
    hair_type: ["dry", "damaged", "dehydrated"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "HUMIT_SH_1L.png",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_hyaloneurine",
    sku: "S005",
    display_name: "Hyaloneurine Face & Hair Serum",
    collection: "Moisture",
    collection_id: "moisture",
    subcollection: "Hyaloneurine",
    subcollection_id: "hyaloneurine",
    description: "Suero Antiedad. Ácido Hialurónico & Elastina. Cara y Cabello.",
    description_enhanced: null,
    key_ingredients: ["hyaluronic acid", "elastin"],
    benefit_claims: ["hidrata cara y cabello", "favorece la elasticidad", "contribuye al aspecto antiedad de la piel", "nutre y suaviza la hebra capilar"],
    hair_type: ["all hair types", "mature hair", "dry hair"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NSERHYA.webp",
    format: "pump_serum_bottle",
    size: "50ml",
  },
  {
    id: "neurone_kerasin_hb_leave_in",
    sku: "T059",
    display_name: "Kerasin HB Leave-In",
    collection: "Restore",
    collection_id: "restore",
    subcollection: "Kerasin HB",
    subcollection_id: "kerasin_hb",
    description: "Tratamiento Pro-Reparación sin Enjuague para Cabello Dañado. Keratina + Ácido Hialurónico + Biotina.",
    description_enhanced: null,
    key_ingredients: ["keratin", "hyaluronic acid", "biotin"],
    benefit_claims: ["repara sin enjuague", "fortalece la hebra", "nutre con keratina y biotina"],
    hair_type: ["damaged", "brittle", "chemically treated"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTKHBLN.webp",
    format: "pump_bottle",
    size: "100ml",
  },
  {
    id: "neurone_kerasin_hb_mask",
    sku: "T058",
    display_name: "Kerasin HB Mask",
    collection: "Restore",
    collection_id: "restore",
    subcollection: "Kerasin HB",
    subcollection_id: "kerasin_hb",
    description: "Mascarilla Pro-Reparación para Cabello Dañado. Keratina + Ácido Hialurónico + Biotina.",
    description_enhanced: null,
    key_ingredients: ["keratin", "hyaluronic acid", "biotin"],
    benefit_claims: ["repara intensamente", "aporta keratina y biotina", "restaura la hebra maltratada"],
    hair_type: ["damaged", "brittle", "porous", "chemically processed"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTKHBMK-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_kerasin_hb_shampoo",
    sku: "L029",
    display_name: "Kerasin HB Shampoo",
    collection: "Restore",
    collection_id: "restore",
    subcollection: "Kerasin HB",
    subcollection_id: "kerasin_hb",
    description: "Champú Reparador para Cabello Dañado. Keratina + Ácido Hialurónico + Biotina.",
    description_enhanced: null,
    key_ingredients: ["keratin", "hyaluronic acid", "biotin"],
    benefit_claims: ["repara", "fortalece", "nutre la hebra capilar"],
    hair_type: ["damaged", "chemically treated", "brittle", "porous"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "kerasinsh_400_web.png",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_licra_web",
    sku: "E016",
    display_name: "Licra Web",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Pasta Efecto Telaraña. Fijación Ligera.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["fijación ligera", "efecto telaraña", "define y da textura"],
    hair_type: ["all hair types", "medium to short hair"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLYCW.webp",
    format: "jar_with_lid",
    size: "70g",
  },
  {
    id: "neurone_lisothermic",
    sku: "T040",
    display_name: "Lisothermic",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Crema Protectora Térmica para Alaciado Temporal.",
    description_enhanced: null,
    key_ingredients: ["thermal protective complex"],
    benefit_claims: ["protege del calor", "favorece el alaciado temporal", "suaviza la hebra"],
    hair_type: ["all hair types", "wavy", "curly hair seeking temporary straightening"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTLISOTH-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_melanin_anti_g",
    sku: "A003",
    display_name: "Melanin Anti G",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Melanin",
    subcollection_id: "melanin",
    description: "Loción Capilar para el Cabello. Tecnología de Péptidos. Efecto Anti-Canas.",
    description_enhanced: null,
    key_ingredients: ["peptides"],
    benefit_claims: ["efecto anti-canas", "tecnología de péptidos", "favorece el aspecto más joven del cabello"],
    hair_type: ["gray hair", "premature gray", "all hair types for prevention"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTMELA.webp",
    format: "spray_applicator_bottle",
    size: "100ml",
  },
  {
    id: "neurone_menthol_ice_shampoo",
    sku: "L026",
    display_name: "Menthol Ice Shampoo",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Menthol Ice",
    subcollection_id: "menthol_ice",
    description: "Champú Refrescante. Fortalecedor, Voluminizador.",
    description_enhanced: null,
    key_ingredients: ["menthol"],
    benefit_claims: ["refresca el cuero cabelludo", "fortalece", "contribuye al volumen"],
    hair_type: ["all hair types", "oily scalp", "fine hair needing volume"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSMICE-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_molding_toner",
    sku: "E007",
    display_name: "Molding Toner",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Crema Gel. Matizante Platinado.",
    description_enhanced: null,
    key_ingredients: ["platinum toning pigments"],
    benefit_claims: ["moldea y estiliza", "matiza tonos no deseados en cabello platinado", "fijación con efecto matizante"],
    hair_type: ["platinum", "silver", "blonde", "gray"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NEMOLON-3.webp",
    format: "jar_with_lid",
    size: "300g",
  },
  {
    id: "neurone_neurona_gloss",
    sku: "T032",
    display_name: "Neurona Gloss",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Suero de Brillo para Cabello. Protección Térmica. Luminosidad. Flexibilidad. Sedosidad.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["brillo instantáneo", "protección térmica", "flexibilidad y sedosidad"],
    hair_type: ["all hair types", "dull hair", "frizzy hair"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTTHERM.webp",
    format: "pump_bottle",
    size: "100ml",
  },
  {
    id: "neurone_neuroxide",
    sku: "",
    display_name: "Neuroxide Cream Developer",
    collection: "Pro Salon / Peroxide",
    collection_id: "pro_salon_peroxide",
    subcollection: "Neuroxide",
    subcollection_id: "neuroxide",
    description: "Peróxido en Crema. Disponible en 5, 10, 20, 30 y 40 volúmenes.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: [],
    hair_type: [],
    price: "0.00",
    msrp: "0.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCNEU-6.webp",
    format: "squeeze_bottle",
    size: "1L",
  },
  {
    id: "neurone_plattina_shampoo",
    sku: "L028",
    display_name: "Plattina Shampoo",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Plattina",
    subcollection_id: "plattina",
    description: "Champú Matizador. Cabello Platinado.",
    description_enhanced: null,
    key_ingredients: ["platinum toning pigments"],
    benefit_claims: ["matiza tonos no deseados", "mantiene el platino brillante", "limpia sin dañar el color"],
    hair_type: ["platinum", "silver", "very light blonde", "gray"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSPLAT-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_plattina_white",
    sku: "D003",
    display_name: "Plattina White",
    collection: "Pro Salon / Bleaching",
    collection_id: "pro_salon_bleaching",
    subcollection: "Plattina White",
    subcollection_id: "plattina_white",
    description: "Polvo Decolorante para el Cabello. No Volátil. Nanotribología Capilar. Fórmula 1+3.",
    description_enhanced: null,
    key_ingredients: ["bleaching agents", "nanotribology complex"],
    benefit_claims: [],
    hair_type: [],
    price: "0.00",
    msrp: "0.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCPLWT.webp",
    format: "jar_with_lid",
    size: "400g",
  },
  {
    id: "neurone_pro_filus",
    sku: "D006",
    display_name: "Pro Filus",
    collection: "Pro Salon / Bleaching",
    collection_id: "pro_salon_bleaching",
    subcollection: "Pro Filus",
    subcollection_id: "pro_filus",
    description: "Polvo Protector para Decoloraciones. Cabello Altamente Procesado.",
    description_enhanced: null,
    key_ingredients: ["protective complex for bleaching"],
    benefit_claims: [],
    hair_type: [],
    price: "0.00",
    msrp: "0.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCPROF.webp",
    format: "large_jar",
    size: "200g",
  },
  {
    id: "neurone_regress",
    sku: "D008",
    display_name: "Regress Color Remover Kit",
    collection: "Pro Salon",
    collection_id: "pro_salon",
    subcollection: "Pro Salon",
    subcollection_id: "pro_salon",
    description: "Extractor de Color para Tinte de Oxidación.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["extrae el color de oxidación", "prepara para recoloración"],
    hair_type: ["all hair types with permanent color"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NREGRE.webp",
    format: "box_kit_2_pieces",
    size: "200ml x2 pieces",
  },
  {
    id: "neurone_resplander_shine",
    sku: "E017",
    display_name: "Resplander Shine",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Spray de Brillo y Acondicionamiento para el Cabello.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["brillo instantáneo", "acondiciona el cabello", "acabado luminoso"],
    hair_type: ["all hair types"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NERESPSH.webp",
    format: "spray_bottle",
    size: "100ml",
  },
  {
    id: "neurone_revenant_color",
    sku: "",
    display_name: "Revenant Color",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Revenant Color",
    subcollection_id: "revenant_color",
    description: "Mascarilla Intensificadora de Color que Ayuda a Reparar el Cabello.",
    description_enhanced: null,
    key_ingredients: ["color pigments", "nourishing complex"],
    benefit_claims: ["intensifica el color", "nutre la hebra", "ayuda a reparar el cabello"],
    hair_type: ["color-treated", "bleached", "all hair types needing color refresh"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTREVCO-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_thermo_dual",
    sku: "T042",
    display_name: "Thermo Dual",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Protector Térmico. Tratamiento que ayuda a Reparar el Cabello.",
    description_enhanced: null,
    key_ingredients: ["thermal protective complex"],
    benefit_claims: ["protege del calor", "ayuda a reparar", "dual action: protector + tratamiento"],
    hair_type: ["all hair types", "heat-styled hair"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTTHERM__1_.webp",
    format: "spray_bottle",
    size: "200ml",
  },
  {
    id: "neurone_total_violet_ink",
    sku: "C180",
    display_name: "Total Violet Ink",
    collection: "Pro Salon / Colour",
    collection_id: "pro_salon_colour",
    subcollection: "Total Violet",
    subcollection_id: "total_violet",
    description: "Concentrado de Pigmento Violeta.",
    description_enhanced: null,
    key_ingredients: ["pure violet pigment concentrate"],
    benefit_claims: [],
    hair_type: [],
    price: "0.00",
    msrp: "0.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCTOVIOK.webp",
    format: "pump_bottle",
    size: "100ml",
  },
  {
    id: "neurone_total_violet_mask",
    sku: "T038",
    display_name: "Total Violet Mask",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Total Violet",
    subcollection_id: "total_violet",
    description: "Mascarilla Acondicionadora Matizante. Neutralizante de Visos Amarillos.",
    description_enhanced: null,
    key_ingredients: ["violet pigments"],
    benefit_claims: ["neutraliza tonos amarillos", "acondiciona", "matiza"],
    hair_type: ["bleached", "highlighted", "platinum", "gray"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTTVIMA-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_total_violet_shampoo",
    sku: "L015",
    display_name: "Total Violet Shampoo",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Total Violet",
    subcollection_id: "total_violet",
    description: "Champú Matizador. Neutraliza Visos Amarillos.",
    description_enhanced: null,
    key_ingredients: ["violet pigments"],
    benefit_claims: ["neutraliza visos amarillos", "matiza", "cuida el color"],
    hair_type: ["bleached", "highlighted", "platinum", "gray"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSTOVIO-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
  {
    id: "neurone_velvety_control",
    sku: "T026",
    display_name: "Velvety Control",
    collection: "Restore",
    collection_id: "restore",
    subcollection: "Velvety Control",
    subcollection_id: "velvety_control",
    description: "Tratamiento Pro Hidratación y Reparación. Sin Enjuague.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["hidratación profunda sin enjuague", "pro reparación", "control del frizz y suavidad"],
    hair_type: ["damaged", "dry", "frizzy", "over-processed"],
    price: "0.00",
    msrp: "0.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTVELCO-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
  },
];

function buildCollections(products: CatalogProduct[]): CatalogCollection[] {
  const colMap = new Map<string, CatalogCollection>();
  for (const p of products) {
    if (!colMap.has(p.collection_id)) {
      colMap.set(p.collection_id, { id: p.collection_id, label: p.collection, subcollections: [], products: [] });
    }
    const col = colMap.get(p.collection_id)!;
    col.products.push(p);
    let sub = col.subcollections.find(s => s.id === p.subcollection_id);
    if (!sub) {
      sub = { id: p.subcollection_id, label: p.subcollection, products: [] };
      col.subcollections.push(sub);
    }
    sub.products.push(p);
  }
  return Array.from(colMap.values()).sort((a, b) => a.label.localeCompare(b.label));
}

export const NEURONE_CATALOG: CatalogCollection[] = buildCollections(NEURONE_PRODUCTS);

export const CATALOG_BY_BRAND: Partial<Record<BrandId, CatalogCollection[]>> = {
  neuroneCosmetics: NEURONE_CATALOG,
};

export function getCatalog(brandId: string): CatalogCollection[] {
  return CATALOG_BY_BRAND[brandId as BrandId] ?? [];
}

export function getProduct(brandId: string, productId: string): CatalogProduct | undefined {
  const catalog = getCatalog(brandId);
  return catalog.flatMap(c => c.products).find(p => p.id === productId);
}
