// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Regenerate: GITHUB_TOKEN=ghp_xxx npx ts-node scripts/generate_catalog.ts
// Last generated: 2026-03-11T21:09:21.012Z

import type { BrandId } from './brands';

// ── INTERFACES ──────────────────────────────────────────────────────────────

export interface CatalogProduct {
  id: string;
  sku: string;
  display_name: string;
  collection: string;
  collection_id: string;
  subcollection: string;
  subcollection_id: string;
  description: string;
  description_enhanced: string | null;
  key_ingredients: string[];
  benefit_claims: string[];
  hair_type: string[];
  price: string;
  msrp: string;
  b2b_only: boolean;
  shopify_visibility: string;
  image_filename: string;
  format: string;
  size: string;
  cross_sell?: string[];
  imagelab?: {
    dominant_hex?: string;
    accent_hex?: string;
    mood?: string;
    packaging_style?: string;
    image_usage?: {
      standard?: { filename?: string; background?: string };
      campaign?: { filename?: string; background?: string };
      dark_available?: boolean;
    };
  };
}

export interface CatalogSubcollection {
  id: string;
  label: string;
  products: CatalogProduct[];
}

export interface CatalogCollection {
  id: string;
  label: string;
  subcollections: CatalogSubcollection[];
  products: CatalogProduct[];
}

// ── NEURONE CATALOG ─────────────────────────────────────────────────────────

const NEURONE_PRODUCTS: CatalogProduct[] = [
  {
    id: "neurone_capissen_lotion",
    sku: "T067",
    display_name: "Capissen Lotion",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Anti-Caída / Capissen",
    subcollection_id: "anti_cada_capissen",
    description: "Loción capilar de uso diario. Ayuda a retrasar la caída prematura del cabello. SIN ENJUAGUE. Su avanzada TECNOLOGÍA DE PÉPTIDOS contribuye a optimizar los ciclos de crecimiento capilar, mejorar la densidad, engrosar y fortalecer el cabello.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["contribuye al aspecto de densidad y fortaleza del cabello", "cuidado del cuero cabelludo"],
    hair_type: ["thinning", "hair loss concern"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "pending",
    image_filename: "NACLOT.webp",
    format: "spray_applicator_bottle",
    size: "100ml",
    cross_sell: ["neurone_capissen_shampoo","neurone_melanin_anti_g"],
    imagelab: {"packaging_style":"spray_applicator_scalp","dominant_hex":"#E8E8E8","accent_hex":"#2A2A2A","lifestyle_context":["scalp treatment routine","hairline application","anti-loss ritual"],"ugc_scenarios":["scalp applicator use","healthy scalp result","professional recommendation context"],"hero_angle":"three_quarter_with_applicator","mood":"clinical, scalp care authority, prevention ritual","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NACLOT.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NACLOT.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_capissen_shampoo",
    sku: "L033",
    display_name: "Capissen Shampoo",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Anti-Caída / Capissen",
    subcollection_id: "anti_cada_capissen",
    description: "Shampoo de uso diario, auxiliar en la prevención de la caída del cabello. Su avanzada TECNOLOGÍA DE PÉPTIDOS contribuye a optimizar los ciclos de crecimiento capilar, mejorar la densidad, engrosar y fortalecer el cabello.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["contribuye al aspecto de densidad", "cuida el cuero cabelludo", "fortalece la hebra capilar"],
    hair_type: ["thinning", "hair loss concern", "fine hair"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "pending",
    image_filename: "NACSHA-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_capissen_lotion"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#F5F5F5","accent_hex":"#1A1A1A","lifestyle_context":["scalp care routine","anti-hair-loss ritual"],"ugc_scenarios":["scalp application","healthy scalp aesthetic","hair density visual"],"hero_angle":"front_portrait","mood":"clean white, clinical scalp care, professional","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NACSHA-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"dark","filename":"CAPISSEN_400_WEB.png","notes":"Fondo negro de estudio para landings, redes y campañas."},"dark_available":false}},
  },
  {
    id: "neurone_neurone_color",
    sku: "",
    display_name: "Neurone Color",
    collection: "Pro Salon / Colour",
    collection_id: "pro_salon_colour",
    subcollection: "Neurone Color",
    subcollection_id: "neurone_color",
    description: "El primer tinte de oxidación creado con tecnología NANO TRIBOLOGÍA CAPILAR que promueve el balance de lubricación de las hebras del cabello (Tribología) para una mejor penetración del color evitando el daño en el cabello y logrando una máxima duración del color con excelente cubrimiento de cana. Más de 70 tonos de oxidación permanente.",
    description_enhanced: null,
    key_ingredients: ["quinoa protein", "nano tribology complex", "oxidative dyes"],
    benefit_claims: [],
    hair_type: [],
    price: "10.00",
    msrp: "10.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCOLOR.webp",
    format: "tube_in_box",
    size: "90ml",
    cross_sell: ["neurone_neuroxide","neurone_density_proff"],
    imagelab: {"packaging_style":"tube_in_premium_box","dominant_hex":"#1A2F5A","accent_hex":"#C8C8A0","lifestyle_context":["salon coloring station","professional color tray","B2B showcase"],"ugc_scenarios":["shade family display","professional application","before/after color result"],"hero_angle":"box_front_portrait","mood":"navy premium, professional colorist authority, permanent color precision","image_usage":{"standard":{"filename":"NCOLOR.webp","background":"white"},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NCOLOR.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_controller",
    sku: "E006",
    display_name: "Controller",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Cera gel de máxima fijación con efecto de aspecto húmedo y con excelente resistencia a la humedad. Su textura permite hacer peinados artísticos o simplemente aplacar cabellos muy rebeldes. Para un estilo definido y controlado.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["fijación extrema", "efecto wet look", "control total del peinado"],
    hair_type: ["all hair types", "medium to short styles"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NECONTR-3.webp",
    format: "jar_with_lid",
    size: "300g",
    cross_sell: ["neurone_molding_toner"],
    imagelab: {"packaging_style":"matte_black_jar","dominant_hex":"#1A1A1A","accent_hex":"#9A9A9A","lifestyle_context":["barbershop","men's grooming","editorial fashion"],"ugc_scenarios":["wet look application","extreme hold demonstration","before/after slick style"],"hero_angle":"top_and_front_duo","mood":"matte black authority, extreme hold, urban grooming","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NECONTR-3.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NECONTR-3.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_density_proff",
    sku: "",
    display_name: "Density Proff",
    collection: "Pro Salon / Peroxide",
    collection_id: "pro_salon_peroxide",
    subcollection: "Density Proff",
    subcollection_id: "density_proff",
    description: "Peróxido en crema estabilizado, su formulación proporciona una consistencia densa que permite tener mayor precisión y fácil manejo. Aumenta el poder de aclaración contribuyendo a mejorar la fijación del pigmento.",
    description_enhanced: null,
    key_ingredients: ["hydrogen peroxide", "high density formula"],
    benefit_claims: [],
    hair_type: [],
    price: "10.00",
    msrp: "10.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCPROF.webp",
    format: "squeeze_bottle",
    size: "1L",
    cross_sell: ["neurone_neurone_color","neurone_plattina_white"],
    imagelab: {"packaging_style":"squeeze_bottle","dominant_hex":"#F5F5F5","accent_hex":"#2C8FBF","lifestyle_context":["salon coloring station","professional developer","B2B context"],"ugc_scenarios":["high density texture","professional mixing","paired with Neurone Color"],"hero_angle":"front_portrait","mood":"clean white, high density professional, salon precision","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NCPROF.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NCPLWT-2-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_depura_shampoo",
    sku: "L021",
    display_name: "Depura Shampoo",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Depura",
    subcollection_id: "depura",
    description: "Formulado a base de carbón activado y otros ingredientes purificantes y regenerantes, logrando una limpieza profunda que elimina impurezas en el cuero cabelludo y cabello, favoreciendo el crecimiento sano de la fibra capilar.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["limpieza profunda", "efecto purificante", "elimina residuos de producto"],
    hair_type: ["all hair types", "oily scalp", "product buildup"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSDEP-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_menthol_ice_shampoo"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#F5F5F5","accent_hex":"#1A1A1A","lifestyle_context":["shower","clean routine","clarifying treatment"],"ugc_scenarios":["product buildup before/after","scalp clarifying routine","clean minimal aesthetic"],"hero_angle":"front_portrait","mood":"white clean minimalism, purifying, detox aesthetic","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NLSDEP-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NLSDEP-1-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_derma_roller",
    sku: "PR041",
    display_name: "Derma Roller",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Anti-Caída",
    subcollection_id: "anti_cada",
    description: "Rodillo de Microagujas de Titanio. Auxiliar para tratar el adelgazamiento capilar.",
    description_enhanced: null,
    key_ingredients: ["titanium microneedles"],
    benefit_claims: ["auxiliar para el cuidado del cuero cabelludo", "contribuye al aspecto del cabello"],
    hair_type: ["thinning hair", "hair loss concern"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "pending",
    image_filename: "NACDR.webp",
    format: "box_with_device",
    size: "1 pieza",
    cross_sell: ["neurone_capissen_lotion","neurone_melanin_anti_g"],
    imagelab: {"packaging_style":"box_with_device","dominant_hex":"#1A2F5A","accent_hex":"#FFFFFF","lifestyle_context":["scalp care routine","professional treatment context","B2B/salon preferred"],"ugc_scenarios":["packaging display","device detail","salon professional use"],"hero_angle":"product_and_packaging_duo","mood":"clinical, professional, scalp authority","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NACDR.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NACDR.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_dy_fazza_color",
    sku: "T062",
    display_name: "DY Fazza Color",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "DY Fazza",
    subcollection_id: "dy_fazza",
    description: "Tratamiento hidratante en dos fases para cabello teñido que desenreda, aportando vitalidad y fuerza. Sus ingredientes ayudan a proteger el color del cabello teñido alargando su duración y evitando el deslave.",
    description_enhanced: null,
    key_ingredients: ["2-phase formula"],
    benefit_claims: ["hidrata el cabello teñido sin enjuague", "nutre la hebra coloreada", "contribuye a prolongar la viveza del color"],
    hair_type: ["color-treated", "dyed", "bleached", "colored hair"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "dyfazzacolor_400_web.png",
    format: "spray_bottle",
    size: "400ml",
    cross_sell: ["neurone_dyfensor_shampoo","neurone_dyfensor_serum","neurone_total_violet_mask"],
    imagelab: {"packaging_style":"spray_bottle","dominant_hex":"#E8A0C8","accent_hex":"#9A3A7A","lifestyle_context":["post-color routine","color maintenance ritual","paired with Dyfensor line"],"ugc_scenarios":["shake-before-use 2-phase visual","application on color-treated hair","color longevity before/after","Color Rescue line pairing"],"hero_angle":"front_portrait","mood":"pink gradient luxury, color protection, vibrant color-care","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"dyfazzacolor_400_web.png","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"dark","filename":"dyfazzacolor_400_web.png","notes":"Fondo negro de estudio para landings, redes y campañas."},"dark_available":true}},
  },
  {
    id: "neurone_dy_fazza",
    sku: "T029",
    display_name: "DY Fazza",
    collection: "Moisture",
    collection_id: "moisture",
    subcollection: "DY Fazza",
    subcollection_id: "dy_fazza",
    description: "Tratamiento nutritivo en dos fases altamente hidratante y desenredante que aporta flexibilidad al cabello para evitar su ruptura. Protege al cabello de los daños causados por el medio ambiente, el sol, las herramientas de calor y procesos químicos controlando el frizz, aportando vitalidad, hidratación, volumen y fuerza.",
    description_enhanced: null,
    key_ingredients: ["2-phase formula"],
    benefit_claims: ["hidrata en profundidad", "nutre la hebra", "sin enjuague — fácil de aplicar"],
    hair_type: ["dry", "dehydrated", "curly", "coarse"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSDYLS-1-1.webp",
    format: "spray_bottle",
    size: "400ml",
    cross_sell: ["neurone_humit_mask","neurone_hyaloneurine"],
    imagelab: {"packaging_style":"spray_bottle","dominant_hex":"#5BB8E8","accent_hex":"#1A4F9A","lifestyle_context":["shower","bathroom counter","post-wash routine"],"ugc_scenarios":["shake before use","spray application","hydration result on hair"],"hero_angle":"front_portrait","mood":"fresh, hydrating, blue ocean energy","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NLSDYLS-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"dark","filename":"dyfazza_400_web.png","notes":"Fondo negro de estudio para landings, redes y campañas."},"dark_available":true}},
  },
  {
    id: "neurone_dyfensor_serum",
    sku: "S006",
    display_name: "Dyfensor Hair Restructuring Serum",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Dyfensor",
    subcollection_id: "dyfensor",
    description: "Suero que recubre las zonas dañadas del cabello brindando una profunda restauración capilar. Protege el color del cabello teñido prolongando su duración para mantener un color radiante y duradero.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["reestructura la hebra", "protege el color", "sella la cutícula"],
    hair_type: ["color-treated", "bleached", "damaged"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NSERCPT-4.webp",
    format: "pump_serum_bottle",
    size: "25ml",
    cross_sell: ["neurone_total_violet_shampoo","neurone_plattina_shampoo"],
    imagelab: {"packaging_style":"slim_pump_serum","dominant_hex":"#F0F0F0","accent_hex":"#8B1A4A","lifestyle_context":["vanity flatlay","post-color treatment","salon finishing"],"ugc_scenarios":["drop application","shine result","serum texture close-up"],"hero_angle":"front_portrait","mood":"minimal, clinical-luxury, color protection","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NSERCPT-4.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"dark","filename":"DYFENSOR_25ML_WEB.png","notes":"Fondo negro de estudio para landings, redes y campañas."},"dark_available":false}},
  },
  {
    id: "neurone_dyfensor_shampoo",
    sku: "L024",
    display_name: "Dyfensor Sulfate Free Shampoo",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Dyfensor",
    subcollection_id: "dyfensor",
    description: "Shampoo libre de sulfatos de acción suave que limpia el cabello cuidando el color y manteniéndolo por más tiempo sin causar irritaciones o molestias al cuero cabelludo. Mantiene los aceites naturales que produce la piel cabelluda reduciendo el efecto de pelo rebelde y encrespado para lograr un cabello más fuerte, saludable y con colores vibrantes.",
    description_enhanced: null,
    key_ingredients: ["sulfate-free cleansing agents"],
    benefit_claims: ["libre de sulfatos", "protege el color del cabello teñido", "limpieza suave que prolonga el color"],
    hair_type: ["color-treated", "dyed", "bleached"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "dyfensorsh_400_web.png",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_dyfensor_serum","neurone_total_violet_mask"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#4A1942","accent_hex":"#8B1A4A","lifestyle_context":["color-care routine","salon color maintenance","paired with Dyfensor Serum"],"ugc_scenarios":["sulfate-free lather","color longevity before/after","color-treated hair care"],"hero_angle":"front_portrait","mood":"deep plum luxury, color protection, sulfate-free clean","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"dyfensorsh_400_web.png","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"dark","filename":"dyfensorsh_400_web.png","notes":"Fondo negro de estudio para landings, redes y campañas."},"dark_available":true}},
  },
  {
    id: "neurone_fanzi_mix",
    sku: "",
    display_name: "Fanzi Mix",
    collection: "Pro Salon / Colour",
    collection_id: "pro_salon_colour",
    subcollection: "Fanzi Mix",
    subcollection_id: "fanzi_mix",
    description: "Crema de color semipermanente acondicionadora para lograr tonos de fantasía. Deja el cabello manejable, sedoso y brillante. Sin peróxido ni amoniaco. Se pueden crear nuevos tonos mezclándolos entre sí o utilizando FANZI MIX TONE DOWN para dar tonos pastel.",
    description_enhanced: null,
    key_ingredients: ["direct dyes / pigments"],
    benefit_claims: [],
    hair_type: [],
    price: "10.00",
    msrp: "10.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCFAMIX.webp",
    format: "squeeze_bottle",
    size: "200ml",
    imagelab: {"packaging_style":"squeeze_bottle_family","lifestyle_context":["colorist station","salon fantasy color","rainbow display"],"ugc_scenarios":["color mixing","fantasy color application","vibrant hair result"],"hero_angle":"family_grid","mood":"vibrant, fantasy, professional colorist, salon exclusive","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NCFAMIX.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NCFAMIX.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_geometry_cream",
    sku: "E012",
    display_name: "Geometry Cream",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Geometry",
    subcollection_id: "geometry",
    description: "Ideal para marcar rizos con efecto elástico y controlar el frizz otorgando brillo y textura al cabello. Enriquecida con Queratina Hidrolizada que otorga resistencia y acondicionamiento al cabello.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["define los rizos con textura cremosa", "aporta elasticidad", "control del frizz"],
    hair_type: ["curly", "wavy", "coily"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NGEOMC-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_geometry_gel"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#9A9A9A","accent_hex":"#4A4A4A","lifestyle_context":["curl styling routine","wash-and-go","curly hair model"],"ugc_scenarios":["cream application texture","defined curls result","paired with Geometry Gel"],"hero_angle":"front_portrait","mood":"sleek silver, curl care, sister product to Geometry Gel","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NGEOMC-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NGEOMC-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_geometry_gel",
    sku: "E008",
    display_name: "Geometry Gel",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Geometry",
    subcollection_id: "geometry",
    description: "Gel líquido que brinda una combinación de estilizado y acondicionamiento. Ideal para otorgar textura, moldear y marcar rizos con efecto elástico y controlar el frizz. Retiene y define los rizos proporcionando una fijación flexible y suave con efecto memoria.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["define los rizos", "aporta elasticidad", "efecto anti-frizz"],
    hair_type: ["curly", "wavy", "coily"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NEGEOGE-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_geometry_cream"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#9A9A9A","accent_hex":"#4A4A4A","lifestyle_context":["curl styling routine","shower to style","editorial curly hair"],"ugc_scenarios":["curl definition result","application on wet hair","before/after frizz"],"hero_angle":"front_portrait","mood":"sleek silver, curl authority, anti-frizz precision","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NEGEOGE-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NEGEOGE-1-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_green_100",
    sku: "T109",
    display_name: "Green 100",
    collection: "Restore",
    collection_id: "restore",
    subcollection: "Green 100",
    subcollection_id: "green_100",
    description: "Serum vegetal para cabello extremadamente reseco, poroso y químicamente procesado. PRODUCTO 100% VERDE. Libre de siliconas, 100% origen vegetal. Humecta, aporta brillo desbordante, controla el frizz, sella la cutícula, protege el color y facilita el deslizamiento de herramientas de estilizado.",
    description_enhanced: null,
    key_ingredients: ["vegetable extracts"],
    benefit_claims: ["restaura la hebra seca y porosa", "nutre con activos vegetales", "favorece la suavidad y flexibilidad"],
    hair_type: ["extremely dry", "porous", "chemically processed", "bleached"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTGREEN-2.webp",
    format: "spray_serum_bottle",
    size: "25ml",
    cross_sell: ["neurone_kerasin_hb_mask","neurone_kerasin_hb_leave_in"],
    imagelab: {"packaging_style":"slim_spray_serum","dominant_hex":"#2A7A3A","accent_hex":"#8BC34A","lifestyle_context":["natural/organic flatlay","dry hair treatment","green aesthetic"],"ugc_scenarios":["extremely dry hair before/after","application","natural ingredients visual"],"hero_angle":"front_portrait","mood":"natural, green, botanical rescue, clean ingredients","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NTGREEN-2.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NTGREEN-2.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_humit_mask",
    sku: "T035",
    display_name: "Humit Mask",
    collection: "Moisture",
    collection_id: "moisture",
    subcollection: "Humit",
    subcollection_id: "humit",
    description: "Mascarilla acondicionadora de alta humectación. Brinda una prolongada y eficaz restauración capilar e intenso acondicionamiento, reduciendo el frizz para una cabellera brillante, suave y controlada.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["hidratación intensa", "acondiciona", "suaviza y aporta brillo"],
    hair_type: ["dry", "damaged", "dehydrated", "over-processed"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTHUMA-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_dy_fazza","neurone_hyaloneurine"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#F5EDD5","accent_hex":"#2C3E6B","lifestyle_context":["bathroom counter","spa treatment aesthetic","shower shelf"],"ugc_scenarios":["mask application","hydrated hair result","before/after dry to moisturized"],"hero_angle":"front_portrait","mood":"warm, creamy, luxurious hydration, spa-like","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NTHUMA-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"dark","filename":"humitmask_400_web.png","notes":"Fondo negro de estudio para landings, redes y campañas."},"dark_available":true}},
  },
  {
    id: "neurone_humit_shampoo",
    sku: "L013",
    display_name: "Humit Shampoo",
    collection: "Moisture",
    collection_id: "moisture",
    subcollection: "Humit",
    subcollection_id: "humit",
    description: "Ideal para cabelleras que sufren de gran deshidratación, ya que genera una prolongada y eficaz restauración capilar. Proporciona un intenso acondicionamiento que mejora notablemente la manejabilidad del cabello, reduciendo el frizz, logrando un cabello brillante, suave y controlado.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["humectación intensa", "acondiciona mientras limpia", "suaviza la hebra seca"],
    hair_type: ["dry", "damaged", "dehydrated"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSHUM-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_humit_mask","neurone_dy_fazza"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#1A5F7A","accent_hex":"#2C3E6B","lifestyle_context":["shower","hydration routine","paired with Humit Mask"],"ugc_scenarios":["creamy lather","hydrated hair result","dry to moisturized transformation"],"hero_angle":"front_portrait","mood":"deep teal, moisture immersion, spa hydration","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NLSHUM-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"dark","filename":"HUMIT_SH_1L.png","notes":"Fondo negro de estudio para landings, redes y campañas."},"dark_available":true}},
  },
  {
    id: "neurone_hyaloneurine",
    sku: "S005",
    display_name: "Hyaloneurine Face & Hair Serum",
    collection: "Moisture",
    collection_id: "moisture",
    subcollection: "Hyaloneurine",
    subcollection_id: "hyaloneurine",
    description: "Fórmula única de suero anti-edad a base de Ácido Hialurónico, Colágeno y Elastina desarrollada para su uso en piel y cabello. Sus ingredientes hacen sinergia para devolver la luminosidad, suavidad y lozanía a la piel y al cabello.",
    description_enhanced: null,
    key_ingredients: ["hyaluronic acid", "elastin"],
    benefit_claims: ["hidrata cara y cabello", "favorece la elasticidad", "contribuye al aspecto antiedad de la piel", "nutre y suaviza la hebra capilar"],
    hair_type: ["all hair types", "mature hair", "dry hair"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NSERHYA.webp",
    format: "pump_serum_bottle",
    size: "50ml",
    cross_sell: ["neurone_humit_mask","neurone_dy_fazza"],
    imagelab: {"packaging_style":"slim_pump_serum","dominant_hex":"#C8D0DC","accent_hex":"#2C3E6B","lifestyle_context":["vanity with skincare","face + hair dual use","clean beauty flatlay"],"ugc_scenarios":["face application","hair serum use","dual-use demonstration"],"hero_angle":"front_portrait","mood":"clean, scientific, hydration luxury, dual-purpose premium","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NSERHYA.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NSERHYA.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_kerasin_hb_leave_in",
    sku: "T059",
    display_name: "Kerasin HB Leave-In",
    collection: "Restore",
    collection_id: "restore",
    subcollection: "Kerasin HB",
    subcollection_id: "kerasin_hb",
    description: "Tratamiento sin enjuague, enriquecido con Ácido Hialurónico, Queratina y Biotina que restauran la elasticidad del cabello dañado y sobre procesado. De textura ligera para una fácil absorción que brinda manejabilidad y gran sedosidad.",
    description_enhanced: null,
    key_ingredients: ["keratin", "hyaluronic acid", "biotin"],
    benefit_claims: ["repara sin enjuague", "fortalece la hebra", "nutre con keratina y biotina"],
    hair_type: ["damaged", "brittle", "chemically treated"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTKHBLN.webp",
    format: "pump_bottle",
    size: "100ml",
    cross_sell: ["neurone_kerasin_hb_shampoo","neurone_kerasin_hb_mask"],
    imagelab: {"packaging_style":"pump_bottle_compact","dominant_hex":"#8B5A2B","accent_hex":"#C47C30","lifestyle_context":["post-wash routine","styling station","travel kit"],"ugc_scenarios":["application on damp hair","no-rinse step in routine","before/after repair"],"hero_angle":"front_portrait","mood":"warm bronze, professional repair, salon quality at home","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NTKHBLN.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NTKHBLN.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_kerasin_hb_mask",
    sku: "T058",
    display_name: "Kerasin HB Mask",
    collection: "Restore",
    collection_id: "restore",
    subcollection: "Kerasin HB",
    subcollection_id: "kerasin_hb",
    description: "Mascarilla reparadora para cabello dañado y sobre procesado. A base de Ácido Hialurónico, Queratina, Biotina y proteínas que fortalecen el cabello, reparándolo y nutriéndolo profundamente para reconstruir la fuerza, mejorar la textura y restaurar su elasticidad.",
    description_enhanced: null,
    key_ingredients: ["keratin", "hyaluronic acid", "biotin"],
    benefit_claims: ["repara intensamente", "aporta keratina y biotina", "restaura la hebra maltratada"],
    hair_type: ["damaged", "brittle", "porous", "chemically processed"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTKHBMK-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_kerasin_hb_shampoo","neurone_kerasin_hb_leave_in"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#F5F0E8","accent_hex":"#8B5A2B","lifestyle_context":["shower","treatment ritual","salon station"],"ugc_scenarios":["deep treatment application","before/after damaged hair","salon mask ritual"],"hero_angle":"front_portrait","mood":"warm bronze on white, premium repair, before/after transformation","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NTKHBMK-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NTKHBMK-1-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_kerasin_hb_shampoo",
    sku: "L029",
    display_name: "Kerasin HB Shampoo",
    collection: "Restore",
    collection_id: "restore",
    subcollection: "Kerasin HB",
    subcollection_id: "kerasin_hb",
    description: "Con Ácido Hialurónico, Queratina y Biotina que ayudan a reparar el daño del cabello maltratado y sobreprocesado desde su interior, para mantener fuerte, lubricada y protegida la superficie del cabello, reduciendo el daño causado por tratamientos químicos, factores ambientales o el uso de herramientas de estilizado.",
    description_enhanced: null,
    key_ingredients: ["keratin", "hyaluronic acid", "biotin"],
    benefit_claims: ["repara", "fortalece", "nutre la hebra capilar"],
    hair_type: ["damaged", "chemically treated", "brittle", "porous"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSKHB-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_kerasin_hb_mask","neurone_kerasin_hb_leave_in"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#8B5A2B","accent_hex":"#C47C30","lifestyle_context":["shower shelf","salon station","product lineup"],"ugc_scenarios":["application lather","damaged-to-healthy transformation","ingredient highlight"],"hero_angle":"front_portrait","mood":"warm, restorative, professional repair","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NLSKHB-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"dark","filename":"kerasinsh_400_web.png","notes":"Fondo negro de estudio para landings, redes y campañas."},"dark_available":true}},
  },
  {
    id: "neurone_licra_web",
    sku: "E016",
    display_name: "Licra Web",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Pasta para el cabello con efecto telaraña. Su fórmula permite dar definición al peinado, con fijación ligera y gran textura al cabello.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["fijación ligera", "efecto telaraña", "define y da textura"],
    hair_type: ["all hair types", "medium to short hair"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLYCW.webp",
    format: "jar_with_lid",
    size: "70g",
    cross_sell: ["neurone_lisothermic","neurone_thermo_dual"],
    imagelab: {"packaging_style":"round_jar","dominant_hex":"#E8E8E8","accent_hex":"#9A9A9A","lifestyle_context":["vanity countertop","barbershop aesthetic","men/women styling"],"ugc_scenarios":["texture application between fingers","before/after texture effect","web effect demonstration"],"hero_angle":"top_and_front_duo","mood":"textured, editorial, minimal, unisex","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NLYCW.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NLYCW.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_lisothermic",
    sku: "T040",
    display_name: "Lisothermic",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Crema de estilizado que ofrece protección contra el calor extremo y reduce los efectos dañinos de las herramientas de calor. Contribuye a lograr un impresionante alaciado temporal, otorgando máxima suavidad al cabello y brillo espectacular. También se puede utilizar como crema de peinar.",
    description_enhanced: null,
    key_ingredients: ["thermal protective complex"],
    benefit_claims: ["protege del calor", "favorece el alaciado temporal", "suaviza la hebra"],
    hair_type: ["all hair types", "wavy", "curly hair seeking temporary straightening"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTLISOTH-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_thermo_dual","neurone_neurona_gloss"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#A8A8A8","accent_hex":"#5A5A5A","lifestyle_context":["styling station","blowdry setup","flat iron routine"],"ugc_scenarios":["heat protection application","smooth blowout result","before/after frizzy to smooth"],"hero_angle":"front_portrait","mood":"sleek silver, professional thermal care, salon-grade precision","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NTLISOTH-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NTLISOTH-1-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_melanin_anti_g",
    sku: "A003",
    display_name: "Melanin Anti G",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Melanin",
    subcollection_id: "melanin",
    description: "Loción capilar para el cabello. Efecto Anti-Canas. De uso diario. Contribuye a reducir el proceso de pérdida de Melanina y activar su generación en el folículo capilar, que se hará visible con el crecimiento del nuevo cabello. Su tecnología de Péptidos contribuye a energizar, nutrir y engrosar la cutícula capilar.",
    description_enhanced: null,
    key_ingredients: ["peptides"],
    benefit_claims: ["efecto anti-canas", "tecnología de péptidos", "favorece el aspecto más joven del cabello"],
    hair_type: ["gray hair", "premature gray", "all hair types for prevention"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTMELA.webp",
    format: "spray_applicator_bottle",
    size: "100ml",
    cross_sell: ["neurone_menthol_ice_shampoo"],
    imagelab: {"packaging_style":"spray_applicator_scalp","dominant_hex":"#E0E0E0","accent_hex":"#2A2A2A","lifestyle_context":["scalp treatment routine","mirror application","hairline focus"],"ugc_scenarios":["scalp applicator in use","before/after gray reduction visual","peptide technology graphic"],"hero_angle":"three_quarter_with_applicator","mood":"clinical precision, anti-aging authority, scalp science","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NTMELA.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NTMELA.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_menthol_ice_shampoo",
    sku: "L026",
    display_name: "Menthol Ice Shampoo",
    collection: "Scalp",
    collection_id: "scalp",
    subcollection: "Menthol Ice",
    subcollection_id: "menthol_ice",
    description: "Shampoo refrescante y fortalecedor que remueve las impurezas y grasa del cuero cabelludo, activando la oxigenación y circulación para estimular el crecimiento capilar y lograr un cabello mucho más suave, notablemente más grueso, resistente y sano.",
    description_enhanced: null,
    key_ingredients: ["menthol"],
    benefit_claims: ["refresca el cuero cabelludo", "fortalece", "contribuye al volumen"],
    hair_type: ["all hair types", "oily scalp", "fine hair needing volume"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSMICE-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_melanin_anti_g"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#F5F5F5","accent_hex":"#1A1A1A","lifestyle_context":["shower","salon","clean minimal flatlay"],"ugc_scenarios":["scalp massage application","clean hair result","mint/ice visual metaphor"],"hero_angle":"front_portrait","mood":"clean, fresh, crisp, minimalist","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NLSMICE-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NLSMICE-1-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_molding_toner",
    sku: "E007",
    display_name: "Molding Toner",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Crema gel de fijación media que funciona para estilizar, moldear, definir rizos y al mismo tiempo matizar el cabello a tonos platinados dándole cuerpo, volumen y brillo. En cabello cano, se logra un tono luminoso platinado.",
    description_enhanced: null,
    key_ingredients: ["platinum toning pigments"],
    benefit_claims: ["moldea y estiliza", "matiza tonos no deseados en cabello platinado", "fijación con efecto matizante"],
    hair_type: ["platinum", "silver", "blonde", "gray"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NEMOLON-3.webp",
    format: "jar_with_lid",
    size: "300g",
    cross_sell: ["neurone_plattina_shampoo","neurone_controller"],
    imagelab: {"packaging_style":"matte_black_jar","dominant_hex":"#1A1A1A","accent_hex":"#C8C8D4","lifestyle_context":["platinum hair styling","barbershop premium","silver hair model"],"ugc_scenarios":["platinum hair application","toning while styling","paired with Plattina line"],"hero_angle":"top_and_front_duo","mood":"matte black luxury, silver nuance, platinum editorial","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NEMOLON-3.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NEMOLON-3.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_neurona_gloss",
    sku: "T032",
    display_name: "Neurona Gloss",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Tratamiento en serum que actúa formando una barrera protectora en el cabello, previniendo la formación de puntas abiertas, controlando el frizz y aportando sedosidad, suavidad, manejabilidad y un intenso brillo.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["brillo instantáneo", "protección térmica", "flexibilidad y sedosidad"],
    hair_type: ["all hair types", "dull hair", "frizzy hair"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NCNEU-6.webp",
    format: "pump_bottle",
    size: "100ml",
    cross_sell: ["neurone_thermo_dual","neurone_lisothermic"],
    imagelab: {"packaging_style":"pump_bottle_compact","dominant_hex":"#E8E8E8","accent_hex":"#9A9A9A","lifestyle_context":["vanity finish","salon finishing station","bright studio light"],"ugc_scenarios":["gloss application","shine result on dark hair","finishing touch"],"hero_angle":"front_portrait","mood":"glossy, luminous, clean minimal, finishing luxury","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NCNEU-6.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NTTHERM.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_neuroxide",
    sku: "",
    display_name: "Neuroxide Cream Developer",
    collection: "Pro Salon / Peroxide",
    collection_id: "pro_salon_peroxide",
    subcollection: "Neuroxide",
    subcollection_id: "neuroxide",
    description: "Peróxido en crema estabilizado con innovador sistema de emulsión y acondicionamiento para una coloración o aclaración del cabello con el menor daño posible a la cutícula y menor irritación al cuero cabelludo promoviendo una extraordinaria penetración de los pigmentos.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: [],
    hair_type: [],
    price: "10.00",
    msrp: "10.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCNEU-6.webp",
    format: "squeeze_bottle",
    size: "1L",
    cross_sell: ["neurone_neurone_color","neurone_plattina_white"],
    imagelab: {"packaging_style":"squeeze_bottle_family","dominant_hex":"#F5F5F5","accent_hex":"#2C3E6B","lifestyle_context":["salon coloring station","professional developer","B2B product lineup"],"ugc_scenarios":["vol selector visual","professional mixing","salon application"],"hero_angle":"family_lineup","mood":"clean white professional, salon precision, oxidative authority","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NCNEU-6.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NCNEU-6.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_plattina_shampoo",
    sku: "L028",
    display_name: "Plattina Shampoo",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Plattina",
    subcollection_id: "plattina",
    description: "Ideal para cabelleras canosas en las que se necesite neutralizar el tono amarillento y lograr un extraordinario color platino. Intensifica y otorga brillo al cabello negro o decolorado y lo mantiene en tonalidades grises con reflejos platinados, haciéndolo lucir con brillo, sedosidad e hidratación.",
    description_enhanced: null,
    key_ingredients: ["platinum toning pigments"],
    benefit_claims: ["matiza tonos no deseados", "mantiene el platino brillante", "limpia sin dañar el color"],
    hair_type: ["platinum", "silver", "very light blonde", "gray"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSPLAT-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_total_violet_mask","neurone_total_violet_shampoo"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#4A1942","accent_hex":"#8B1A4A","lifestyle_context":["salon vanity","platinum hair model","luxury flatlay"],"ugc_scenarios":["before/after platinum maintenance","application","color comparison"],"hero_angle":"front_portrait","mood":"luxurious, deep purple, salon-grade exclusivity","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NLSPLAT-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NLSPLAT-1-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_plattina_white",
    sku: "D003",
    display_name: "Plattina White",
    collection: "Pro Salon / Bleaching",
    collection_id: "pro_salon_bleaching",
    subcollection: "Plattina White",
    subcollection_id: "plattina_white",
    description: "Polvo decolorante con tecnología NANO TRIBOLOGÍA CAPILAR, que permite reducir el daño al cabello durante el proceso de la decoloración y menor grado de irritación sobre el cuero cabelludo. Sus ingredientes actúan interna y externamente logrando una decoloración homogénea con un cabello suave y con brillo.",
    description_enhanced: null,
    key_ingredients: ["bleaching agents", "nanotribology complex"],
    benefit_claims: [],
    hair_type: [],
    price: "10.00",
    msrp: "10.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCPLWT.webp",
    format: "jar_with_lid",
    size: "400g",
    cross_sell: ["neurone_neuroxide","neurone_density_proff"],
    imagelab: {"packaging_style":"professional_jar","dominant_hex":"#F5F5F5","accent_hex":"#2C3E6B","lifestyle_context":["salon coloring station","professional bleaching setup","B2B showcase"],"ugc_scenarios":["product display","professional bleaching process","before/after blonde"],"hero_angle":"front_portrait","mood":"clean white professional, salon-grade precision","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NCPLWT.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NCPLWT.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_pro_filus",
    sku: "D006",
    display_name: "Pro Filus",
    collection: "Pro Salon / Bleaching",
    collection_id: "pro_salon_bleaching",
    subcollection: "Pro Filus",
    subcollection_id: "pro_filus",
    description: "Polvo protector de la hebra capilar para decoloraciones en el cabello altamente procesado. Su fórmula ayuda a combatir los daños que el cabello sufre durante estos procesos, reduciendo la rotura, reparándolo y manteniendo su integridad.",
    description_enhanced: null,
    key_ingredients: ["protective complex for bleaching"],
    benefit_claims: [],
    hair_type: [],
    price: "10.00",
    msrp: "10.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCPLWT-2-1.webp",
    format: "large_jar",
    size: "200g",
    cross_sell: ["neurone_plattina_white","neurone_neuroxide"],
    imagelab: {"packaging_style":"large_matte_black_jar","dominant_hex":"#1A1A1A","accent_hex":"#C47C30","lifestyle_context":["bleaching station","professional colorist setup","B2B showcase"],"ugc_scenarios":["product display","professional bleaching protection context","before/after highly processed hair"],"hero_angle":"front_portrait","mood":"matte black authority, professional protection, salon-exclusive premium","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NCPLWT-2-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NCPROF.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_regress",
    sku: "D008",
    display_name: "Regress Color Remover Kit",
    collection: "Pro Salon",
    collection_id: "pro_salon",
    subcollection: "Pro Salon",
    subcollection_id: "pro_salon",
    description: "Sistema para la extracción de color artificial que revierte el proceso del tinte de oxidación regresando el cabello a su melanina original. No contiene amoniaco, decolorante ni formaldehído.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["extrae el color de oxidación", "prepara para recoloración"],
    hair_type: ["all hair types with permanent color"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NREGRE.webp",
    format: "box_kit_2_pieces",
    size: "200ml x2 pieces",
    imagelab: {"packaging_style":"premium_box_kit","dominant_hex":"#1A2F5A","accent_hex":"#FFFFFF","lifestyle_context":["salon professional station","colorist toolkit","B2B product showcase"],"ugc_scenarios":["professional application","before/after color removal","salon context only"],"hero_angle":"front_portrait","mood":"professional, authoritative, navy precision, salon-exclusive","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NREGRE.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NREGRE.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_resplander_shine",
    sku: "E017",
    display_name: "Resplander Shine",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Spray de brillo y acondicionamiento que contribuye a dar al cabello un aspecto vibrante, luminoso, hidratado y saludable, incluso en cabello dañado y sobre procesado. Su fórmula no grasosa y ligera acondiciona dando sedosidad y suavidad al cabello.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["brillo instantáneo", "acondiciona el cabello", "acabado luminoso"],
    hair_type: ["all hair types"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NERESPSH.webp",
    format: "spray_bottle",
    size: "100ml",
    cross_sell: ["neurone_neurona_gloss","neurone_thermo_dual"],
    imagelab: {"packaging_style":"spray_bottle_metallic","dominant_hex":"#6A6A6A","accent_hex":"#C8C8C8","lifestyle_context":["finishing touch","salon finishing station","photo shoot prep"],"ugc_scenarios":["shine spray in action","luminous hair close-up","editorial gloss"],"hero_angle":"front_portrait","mood":"gunmetal editorial, instant luminosity, photo-ready finish","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NERESPSH.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NERESPSH.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_revenant_color",
    sku: "",
    display_name: "Revenant Color",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Revenant Color",
    subcollection_id: "revenant_color",
    description: "Mascarilla nutritiva de color semipermanente que realza el tono del color existente e intensifica reflejos, dando al cabello un aspecto sedoso y gran luminosidad. Todos los tonos son intermezclables para personalizar y crear nuevos tonos.",
    description_enhanced: null,
    key_ingredients: ["color pigments", "nourishing complex"],
    benefit_claims: ["intensifica el color", "nutre la hebra", "ayuda a reparar el cabello"],
    hair_type: ["color-treated", "bleached", "all hair types needing color refresh"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTREVCO-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_total_violet_shampoo","neurone_plattina_shampoo"],
    imagelab: {"packaging_style":"premium_pump_bottle_family","lifestyle_context":["color studio","salon station","rainbow lineup display"],"ugc_scenarios":["variant selector","color intensity before/after","shade match consultation"],"hero_angle":"family_lineup","mood":"rich color spectrum, salon professional, color artistry","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NTREVCO-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NTREVCO-1-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_thermo_dual",
    sku: "T042",
    display_name: "Thermo Dual",
    collection: "Styling",
    collection_id: "styling",
    subcollection: "Styling",
    subcollection_id: "styling",
    description: "Protector térmico de doble acción. Protege al cabello del calor intenso de los dispositivos térmicos y a la vez repara los daños causados a la cutícula sin dejarlo pesado ni grasoso. Brinda máxima suavidad e impresionante brillo.",
    description_enhanced: null,
    key_ingredients: ["thermal protective complex"],
    benefit_claims: ["protege del calor", "ayuda a reparar", "dual action: protector + tratamiento"],
    hair_type: ["all hair types", "heat-styled hair"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTTHERM__1_.webp",
    format: "spray_bottle",
    size: "200ml",
    cross_sell: ["neurone_lisothermic","neurone_neurona_gloss"],
    imagelab: {"packaging_style":"spray_bottle_premium","dominant_hex":"#5A5A5A","accent_hex":"#9A9A9A","lifestyle_context":["styling station","flat iron setup","blowdry routine"],"ugc_scenarios":["spray before heat","heat tool + protector","damage prevention concept"],"hero_angle":"front_portrait","mood":"dark metallic, heat precision, dual-function professional","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NTTHERM__1_.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"dark","filename":"NTTHERM.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":true}},
  },
  {
    id: "neurone_total_violet_ink",
    sku: "C180",
    display_name: "Total Violet Ink",
    collection: "Pro Salon / Colour",
    collection_id: "pro_salon_colour",
    subcollection: "Total Violet",
    subcollection_id: "total_violet",
    description: "Pigmento puro violeta mega concentrado, ideal para eliminar visos naranjas o amarillos y dar luz a los reflejos rubios platinados. Se puede mezclar con el producto que más se adapte al cabello, ya sea tinte, shampoo, acondicionador, mascarillas, etc.",
    description_enhanced: null,
    key_ingredients: ["pure violet pigment concentrate"],
    benefit_claims: [],
    hair_type: [],
    price: "10.00",
    msrp: "10.00",
    b2b_only: true,
    shopify_visibility: "pending",
    image_filename: "NCTOVIOK.webp",
    format: "pump_bottle",
    size: "100ml",
    cross_sell: ["neurone_fanzi_mix","neurone_plattina_shampoo"],
    imagelab: {"packaging_style":"pump_bottle_compact","dominant_hex":"#F5F5F5","accent_hex":"#2C3E6B","lifestyle_context":["colorist station","professional toning","B2B context"],"ugc_scenarios":["pigment dropper technique","professional toning result","salon application"],"hero_angle":"front_portrait","mood":"clinical white, concentrated pigment, professional colorist tool","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NCTOVIOK.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NCTOVIOK.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_total_violet_mask",
    sku: "T038",
    display_name: "Total Violet Mask",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Total Violet",
    subcollection_id: "total_violet",
    description: "Mascarilla acondicionadora para neutralizar visos amarillos en cabello cano y rubio logrando tonos platinados. Brinda un efecto reparador inmediato aportando gran humectación e increíble suavidad para mayor acondicionamiento del cabello, reduciendo el frizz y aportando brillo.",
    description_enhanced: null,
    key_ingredients: ["violet pigments"],
    benefit_claims: ["neutraliza tonos amarillos", "acondiciona", "matiza"],
    hair_type: ["bleached", "highlighted", "platinum", "gray"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTTVIMA-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_total_violet_shampoo","neurone_plattina_shampoo"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#8B8AC8","accent_hex":"#8B1A4A","lifestyle_context":["salon counter","bathroom vanity","flatlay with blonde hair"],"ugc_scenarios":["before/after toning","application on wet hair","texture close-up"],"hero_angle":"front_portrait","mood":"cool, sophisticated, violet luxury","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NTTVIMA-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NTTVIMA-1-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_total_violet_shampoo",
    sku: "L015",
    display_name: "Total Violet Shampoo",
    collection: "Color Rescue",
    collection_id: "color_rescue",
    subcollection: "Total Violet",
    subcollection_id: "total_violet",
    description: "Recomendado para mantener un rubio luminoso, pues neutraliza los visos amarillos sin resecar el cabello. Tiene una alta concentración de proteína, oligosacáridos, vitaminas y acondicionadores que brindan una profunda suavidad y manejabilidad dando brillo al cabello.",
    description_enhanced: null,
    key_ingredients: ["violet pigments"],
    benefit_claims: ["neutraliza visos amarillos", "matiza", "cuida el color"],
    hair_type: ["bleached", "highlighted", "platinum", "gray"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NLSTOVIO-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_total_violet_mask","neurone_plattina_shampoo"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#4A1942","accent_hex":"#8B1A4A","lifestyle_context":["salon","bathroom vanity","paired with Total Violet Mask"],"ugc_scenarios":["application","lather on blonde hair","before/after yellow tones"],"hero_angle":"front_portrait","mood":"deep luxurious purple, violet correction","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NLSTOVIO-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NLSTOVIO-1-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
  {
    id: "neurone_velvety_control",
    sku: "T026",
    display_name: "Velvety Control",
    collection: "Restore",
    collection_id: "restore",
    subcollection: "Velvety Control",
    subcollection_id: "velvety_control",
    description: "Tratamiento nutritivo profundo sin enjuague, altamente higroscópico. Aporta una increíble textura aterciopelada sin dejar una sensación grasosa. Es perfecto para cabellos secos, sin vitalidad y sin control.",
    description_enhanced: null,
    key_ingredients: [],
    benefit_claims: ["hidratación profunda sin enjuague", "pro reparación", "control del frizz y suavidad"],
    hair_type: ["damaged", "dry", "frizzy", "over-processed"],
    price: "10.00",
    msrp: "10.00",
    b2b_only: false,
    shopify_visibility: "public",
    image_filename: "NTVELCO-1-1.webp",
    format: "pump_bottle",
    size: "400ml",
    cross_sell: ["neurone_kerasin_hb_mask","neurone_green_100"],
    imagelab: {"packaging_style":"premium_pump_bottle","dominant_hex":"#8B5A2B","accent_hex":"#C47C30","lifestyle_context":["post-wash routine","styling station","repair ritual"],"ugc_scenarios":["leave-in application","velvet smooth hair result","before/after damaged hair"],"hero_angle":"front_portrait","mood":"warm bronze luxury, deep repair, velvety smooth finish","image_usage":{"standard":{"context":["shopify_product_page","shopify_collection","shopify_cart"],"background":"white","filename":"NTVELCO-1-1.webp","notes":"Fondo blanco. Estándar para tienda B2C y Portal Pro."},"campaign":{"context":["landing_page","social_media","ads","email_header"],"background":"white","filename":"NTVELCO-1-1.webp","notes":"Sin versión dark disponible — usar imagen estándar hasta nueva sesión de fotos."},"dark_available":false}},
  },
];

function buildCollections(products: CatalogProduct[]): CatalogCollection[] {
  const colMap = new Map<string, CatalogCollection>();
  for (const p of products) {
    if (!colMap.has(p.collection_id)) {
      colMap.set(p.collection_id, { id: p.collection_id, label: p.collection, subcollections: [], products: [] });
    }
    const col = colMap.get(p.collection_id)!;
    col.products.push(p);
    let sub = col.subcollections.find(s => s.id === p.subcollection_id);
    if (!sub) {
      sub = { id: p.subcollection_id, label: p.subcollection, products: [] };
      col.subcollections.push(sub);
    }
    sub.products.push(p);
  }
  return Array.from(colMap.values()).sort((a, b) => a.label.localeCompare(b.label));
}

export const NEURONE_CATALOG: CatalogCollection[] = buildCollections(NEURONE_PRODUCTS);

export const CATALOG_BY_BRAND: Partial<Record<BrandId, CatalogCollection[]>> = {
  neuroneCosmetics: NEURONE_CATALOG,
};

export function getCatalog(brandId: string): CatalogCollection[] {
  return CATALOG_BY_BRAND[brandId as BrandId] ?? [];
}

export function getProduct(brandId: string, productId: string): CatalogProduct | undefined {
  const catalog = getCatalog(brandId);
  return catalog.flatMap(c => c.products).find(p => p.id === productId);
}
